package com.github.novamage.svalidator

import com.github.novamage.svalidator.validation.{ValidationResult, ValidationWithData}

import scala.language.implicitConversions

package object testing {

  /** Provides extensions for testing validation summaries generated by validators
    */
  implicit def ShouldExtensions[A](validationSummary: ValidationResult[A]): ShouldExtensions[A] = new ShouldExtensions(validationSummary)
}
